sudo: false
language: bash
os:
  - linux

script:
  - export ARDUINOVER=arduino-1.6.8
  - ( cd "$HOME" && wget -q "http://downloads.arduino.cc/${ARDUINOVER}-linux64.tar.xz" && tar xf ${ARDUINOVER}-linux64.tar.xz ) &
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16 &
  - export DISPLAY=:1.0
  - export ARDUINOIDE="$HOME/$ARDUINOVER"
  - export ARDUINOSDK="$ARDUINOIDE"/hardware/esp8266com
  - mkdir -p "$ARDUINOSDK" && ( cd "$ARDUINOSDK" && git clone -q https://github.com/Adam5Wu/Arduino.git esp8266 ) &
  - export PATH="$ARDUINOIDE:$PATH"
  - wait && export SKETCHBOOK=`arduino --get-pref sketchbook.path`
  - export SKETCHLIB="$SKETCHBOOK"/libraries
  - mkdir -p "$SKETCHLIB"
  - cp -r "$TRAVIS_BUILD_DIR" "$SKETCHLIB"/ESPAsyncWebServer &
  - git clone -q https://github.com/bblanchon/ArduinoJson "$SKETCHLIB"/ArduinoJson &
  - git clone -q https://github.com/me-no-dev/ESPAsyncTCP "$SKETCHLIB"/ESPAsyncTCP &
  - git clone -q https://github.com/Adam5Wu/ESPVFATFS.git "$SKETCHLIB"/ESPVFATFS &
  - ( cd "$ARDUINOSDK"/esp8266/tools && python get.py ) &
  - source "$TRAVIS_BUILD_DIR"/travis/common.sh
  - wait && build_sketches arduino "$SKETCHLIB"/ESPAsyncWebServer esp8266 generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=115200,FlashSize=2M

notifications:
  email:
    on_success: change
    on_failure: change
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/60e65d0c78ea0a920347
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
